INFO 2025-03-29 00:02:35,354 autoreload 43924 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:02:35,743 autoreload 47268 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:03:05,745 autoreload 47268 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:03:06,026 autoreload 47650 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:03:57,493 autoreload 47650 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:03:57,843 autoreload 48273 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:04:52,419 autoreload 48273 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:04:52,754 autoreload 48926 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:05:49,284 autoreload 48926 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 00:05:49,604 autoreload 49645 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:06:53,302 autoreload 49645 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/serializers/client_serializer.py changed, reloading.
INFO 2025-03-29 00:06:53,677 autoreload 50419 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:07:16,422 autoreload 50419 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:07:16,730 autoreload 50714 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:08:44,144 autoreload 50714 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 00:08:44,453 autoreload 51755 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:09:03,169 autoreload 51755 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 00:09:03,534 autoreload 52010 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:09:46,745 autoreload 52010 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 00:09:47,109 autoreload 52538 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:10:09,870 autoreload 52538 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 00:10:10,154 autoreload 52833 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:12:27,660 autoreload 52833 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 00:12:28,015 autoreload 54475 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:14:54,499 autoreload 56293 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:16:45,315 autoreload 57652 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:18:29,255 autoreload 57652 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/client.py changed, reloading.
INFO 2025-03-29 00:18:29,629 autoreload 58895 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:18:59,587 autoreload 58895 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:18:59,909 autoreload 59291 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:19:04,289 autoreload 59291 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:19:04,507 autoreload 59348 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 00:21:26,228 log 59348 6126153728 Forbidden: /api/clients/PE
ERROR 2025-03-29 00:21:33,119 exception 59348 6126153728 Ocurrió una excepción: 'ClientUseCase' object has no attribute 'page_size'
ERROR 2025-03-29 00:21:33,120 exception 59348 6126153728 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py", line 19, in get
    return use_case.get()
           ~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py", line 49, in get
    paginator = Paginator(clients, per_page=self.page_size)
                                            ^^^^^^^^^^^^^^
AttributeError: 'ClientUseCase' object has no attribute 'page_size'

ERROR 2025-03-29 00:21:33,121 log 59348 6126153728 Internal Server Error: /api/clients/PE
INFO 2025-03-29 00:21:59,627 autoreload 59348 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 00:22:00,024 autoreload 61494 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:29:49,957 autoreload 61494 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api_sataiga/handlers/mongodb_handler.py changed, reloading.
INFO 2025-03-29 00:29:50,306 autoreload 67156 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:32:23,513 autoreload 67156 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:32:23,886 autoreload 69041 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:32:43,653 autoreload 69041 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:32:43,977 autoreload 69295 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:33:51,879 autoreload 69295 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:33:52,205 autoreload 70115 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:34:04,709 autoreload 70115 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:34:05,038 autoreload 70297 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:34:12,449 autoreload 70297 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:34:12,794 autoreload 70381 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:34:23,226 autoreload 70381 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:34:23,540 autoreload 70541 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:34:35,065 autoreload 70541 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:34:35,362 autoreload 70677 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:35:50,395 autoreload 70677 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 00:35:50,685 autoreload 71594 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:35:59,101 autoreload 71594 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 00:35:59,365 autoreload 71705 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:36:09,844 autoreload 71705 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 00:36:10,133 autoreload 71845 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:36:30,924 autoreload 71845 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 00:36:31,249 autoreload 72105 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:36:36,624 autoreload 72105 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 00:36:36,920 autoreload 72188 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 00:37:16,399 log 72188 6168031232 Forbidden: /api/client/67e736d4d0486aad300b0794
INFO 2025-03-29 00:38:32,262 autoreload 72188 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:38:32,637 autoreload 73588 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:38:44,176 autoreload 73588 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:38:44,500 autoreload 73730 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:38:58,070 autoreload 73730 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:38:58,344 autoreload 73914 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:40:11,243 autoreload 73914 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 00:40:11,557 autoreload 74788 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:41:01,983 autoreload 74788 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:41:02,317 autoreload 75414 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:42:32,838 autoreload 75414 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 00:42:33,211 autoreload 76513 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 00:44:25,528 autoreload 76513 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 00:44:25,862 autoreload 77850 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 00:44:52,946 log 77850 6171881472 Forbidden: /api/client/67e7382e2ac8c2024c266180
WARNING 2025-03-29 00:46:40,143 log 77850 6188707840 Forbidden: /api/client/67e742dd0eb6bf69fbdfb90f
INFO 2025-03-29 14:36:55,992 autoreload 77850 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 14:36:56,712 autoreload 37923 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:45:09,582 autoreload 37923 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/user_use_case.py changed, reloading.
INFO 2025-03-29 14:45:09,930 autoreload 43915 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:45:12,341 autoreload 43915 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/role_use_case.py changed, reloading.
INFO 2025-03-29 14:45:12,520 autoreload 43975 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:45:17,815 autoreload 43975 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 14:45:18,058 autoreload 44034 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:54:05,279 autoreload 44034 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 14:54:05,642 autoreload 50390 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:54:21,251 autoreload 50390 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/supplier.py changed, reloading.
INFO 2025-03-29 14:54:21,548 autoreload 50597 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:54:30,010 autoreload 50597 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 14:54:30,289 autoreload 50712 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 14:55:49,283 autoreload 50712 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 14:55:49,596 autoreload 51659 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 14:57:23,359 log 51659 6155464704 Forbidden: /api/suppliers
WARNING 2025-03-29 14:59:10,072 log 51659 6172291072 Bad Request: /api/suppliers
ERROR 2025-03-29 14:59:16,224 exception 51659 6172291072 Ocurrió una excepción: "Got KeyError when attempting to get a value for field `email` on serializer `SupplierSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'email'."
ERROR 2025-03-29 14:59:16,240 exception 51659 6172291072 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 102, in get_attribute
    instance = instance[attr]
               ~~~~~~~~^^^^^^
KeyError: 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/supplier.py", line 15, in get
    return use_case.get()
           ~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/supplier_use_case.py", line 42, in get
    SupplierSerializer(page.object_list, many=True).data
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 470, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `email` on serializer `SupplierSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'email'."

ERROR 2025-03-29 14:59:16,240 log 51659 6172291072 Internal Server Error: /api/suppliers
INFO 2025-03-29 15:00:37,859 autoreload 51659 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/supplier_use_case.py changed, reloading.
INFO 2025-03-29 15:00:38,210 autoreload 55134 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 15:01:21,546 autoreload 55134 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/supplier.py changed, reloading.
INFO 2025-03-29 15:01:21,860 autoreload 55664 8545306688 Watching for file changes with StatReloader
ERROR 2025-03-29 15:02:06,596 exception 55664 6165164032 Ocurrió una excepción: "Got KeyError when attempting to get a value for field `contact` on serializer `SupplierSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'contact'."
ERROR 2025-03-29 15:02:06,601 exception 55664 6165164032 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 102, in get_attribute
    instance = instance[attr]
               ~~~~~~~~^^^^^^
KeyError: 'contact'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/supplier.py", line 15, in get
    return use_case.get()
           ~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/supplier_use_case.py", line 42, in get
    SupplierSerializer(page.object_list, many=True).data
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 470, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `contact` on serializer `SupplierSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'contact'."

ERROR 2025-03-29 15:02:06,602 log 55664 6165164032 Internal Server Error: /api/suppliers
INFO 2025-03-29 15:02:31,968 autoreload 55664 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/supplier.py changed, reloading.
INFO 2025-03-29 15:02:32,308 autoreload 56520 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 15:03:24,504 log 56520 6203174912 Forbidden: /api/supplier/67e80b6355e42cc47cd7087f
WARNING 2025-03-29 15:06:39,421 log 56520 6220001280 Forbidden: /api/supplier/67e80c40b212b03003ed5b84
INFO 2025-03-29 15:12:50,577 autoreload 56520 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 15:12:50,925 autoreload 64044 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 15:14:20,494 autoreload 64044 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 15:14:20,878 autoreload 65233 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 15:18:58,851 autoreload 65233 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 15:18:59,229 autoreload 68600 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 15:22:56,231 autoreload 68600 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/supplier_use_case.py changed, reloading.
INFO 2025-03-29 15:22:56,612 autoreload 71457 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 15:23:14,289 autoreload 71457 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 15:23:14,565 autoreload 71691 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 15:23:50,751 autoreload 71691 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/prototype.py changed, reloading.
INFO 2025-03-29 15:23:51,064 autoreload 72131 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:23:29,977 autoreload 72131 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/supplier_use_case.py changed, reloading.
INFO 2025-03-29 16:23:30,376 autoreload 86162 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:23:38,827 autoreload 86162 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/client_use_case.py changed, reloading.
INFO 2025-03-29 16:23:39,103 autoreload 86295 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:30:41,051 autoreload 86295 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/user_use_case.py changed, reloading.
INFO 2025-03-29 16:30:41,407 autoreload 91364 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:30:52,951 autoreload 91364 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/user_use_case.py changed, reloading.
INFO 2025-03-29 16:30:53,254 autoreload 91532 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:31:26,327 autoreload 91532 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/user_use_case.py changed, reloading.
INFO 2025-03-29 16:31:26,659 autoreload 91936 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:43:47,462 autoreload 91936 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 16:43:47,828 autoreload 1200 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:45:34,956 autoreload 1200 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 16:45:35,253 autoreload 2477 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:45:50,732 autoreload 2477 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/client.py changed, reloading.
INFO 2025-03-29 16:45:51,031 autoreload 2692 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:46:03,506 autoreload 2692 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/prototype.py changed, reloading.
INFO 2025-03-29 16:46:03,810 autoreload 2848 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:46:10,137 autoreload 2848 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 16:46:10,432 autoreload 2935 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:46:27,991 autoreload 2935 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 16:46:28,307 autoreload 3168 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 16:49:04,510 autoreload 3168 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 16:49:04,862 autoreload 5045 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:02:16,604 autoreload 5045 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:02:16,998 autoreload 14703 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:02:35,762 autoreload 14703 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:02:36,068 autoreload 14939 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:07:01,276 autoreload 14939 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:07:01,677 autoreload 18191 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:07:52,224 autoreload 18191 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:07:52,547 autoreload 18806 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:09:14,004 autoreload 18806 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:09:14,299 autoreload 19812 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:11:44,833 autoreload 19812 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:11:45,193 autoreload 21599 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:11:52,637 autoreload 21599 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:11:52,964 autoreload 21709 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:13:30,950 autoreload 21709 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:13:31,254 autoreload 22922 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:13:33,624 autoreload 22922 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:13:33,837 autoreload 22954 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:14:28,458 autoreload 22954 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:14:28,828 autoreload 23630 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:14:53,703 autoreload 23630 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:14:53,973 autoreload 23947 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:18:56,938 autoreload 23947 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:18:57,260 autoreload 26859 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:19:07,756 autoreload 26859 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:19:08,079 autoreload 26992 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:19:36,031 autoreload 26992 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:19:36,376 autoreload 27354 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:20:00,303 autoreload 27354 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:20:00,582 autoreload 27672 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:21:28,279 autoreload 27672 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:21:28,604 autoreload 28747 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:21:31,905 autoreload 28747 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:21:32,099 autoreload 28804 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:24:55,391 autoreload 28804 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:24:55,739 autoreload 31304 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:25:05,199 autoreload 31304 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:25:05,504 autoreload 31439 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 17:25:22,908 log 31439 6189248512 Bad Request: /api/prototypes
INFO 2025-03-29 17:26:26,915 autoreload 31439 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:26:27,310 autoreload 32427 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 17:26:30,657 autoreload 32427 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/prototype_use_case.py changed, reloading.
INFO 2025-03-29 17:26:30,850 autoreload 32487 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:06:22,433 autoreload 32487 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 19:06:22,907 autoreload 73998 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:08:36,655 autoreload 73998 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/__init__.py changed, reloading.
INFO 2025-03-29 19:08:37,006 autoreload 75662 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:19:45,044 autoreload 83766 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:23:29,867 autoreload 86454 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:23:40,355 autoreload 86454 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:23:40,683 autoreload 86590 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:23:49,092 autoreload 86590 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:23:49,372 autoreload 86698 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:23:58,809 autoreload 86698 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:23:59,113 autoreload 86829 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:24:08,546 autoreload 86829 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:24:08,870 autoreload 86962 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:24:48,072 autoreload 86962 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:24:48,358 autoreload 87443 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:25:21,498 autoreload 87865 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:25:32,067 autoreload 87865 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:25:32,446 autoreload 88002 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:25:33,687 autoreload 88002 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:25:33,874 autoreload 88030 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:25:38,091 autoreload 88094 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:28:33,869 autoreload 88094 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:28:34,215 autoreload 90238 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:28:43,274 autoreload 90353 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:29:10,559 autoreload 90699 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:29:23,169 autoreload 90699 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:29:23,459 autoreload 90856 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:29:26,785 autoreload 90856 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:29:27,075 autoreload 90914 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:29:36,571 autoreload 90914 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:29:36,848 autoreload 91045 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:30:22,260 autoreload 91045 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:30:22,596 autoreload 91603 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:30:34,096 autoreload 91603 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:30:34,348 autoreload 91761 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:30:39,529 autoreload 91761 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:30:39,759 autoreload 91820 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:31:41,509 autoreload 91820 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:31:41,830 autoreload 92577 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:31:49,889 autoreload 92694 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:32:29,103 autoreload 92694 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:32:29,409 autoreload 93175 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:32:35,774 autoreload 93175 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:32:36,067 autoreload 93263 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:34:06,621 autoreload 93263 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:34:06,963 autoreload 94356 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:34:08,099 autoreload 94356 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:34:08,285 autoreload 94388 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:34:14,699 autoreload 94388 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:34:14,908 autoreload 94470 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:34:56,752 autoreload 94988 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:04,195 autoreload 94988 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:04,412 autoreload 95097 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:07,692 autoreload 95097 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:07,906 autoreload 95155 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:17,305 autoreload 95155 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:17,629 autoreload 95263 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:33,195 autoreload 95263 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:33,474 autoreload 95467 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:37,818 autoreload 95467 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:38,007 autoreload 95525 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:47,404 autoreload 95525 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:47,625 autoreload 95656 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:35:56,009 autoreload 95656 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:35:56,232 autoreload 95762 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:36:10,722 autoreload 95762 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:36:11,028 autoreload 95943 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:36:14,348 autoreload 95943 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/models/material.py changed, reloading.
INFO 2025-03-29 19:36:14,559 autoreload 95999 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 19:36:44,980 autoreload 96370 8545306688 Watching for file changes with StatReloader
WARNING 2025-03-29 20:08:14,528 log 96370 6170505216 Bad Request: /api/catalogs
INFO 2025-03-29 20:08:31,661 autoreload 96370 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:08:32,097 autoreload 18685 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:20:33,794 autoreload 18685 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:20:34,185 autoreload 27490 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:21:09,295 autoreload 27490 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py changed, reloading.
INFO 2025-03-29 20:21:09,623 autoreload 27937 8545306688 Watching for file changes with StatReloader
ERROR 2025-03-29 20:21:49,757 exception 27937 6135328768 Ocurrió una excepción: Object of type ObjectId is not JSON serializable
ERROR 2025-03-29 20:21:49,762 exception 27937 6135328768 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py", line 15, in get
    return use_case.get()
           ~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py", line 21, in get
    return ok(catalogs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/helpers/http_responses.py", line 42, in ok
    response = build_response_no_message(data)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/helpers/http_responses.py", line 26, in build_response_no_message
    return JsonResponse(data, safe=False)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/http/response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ObjectId is not JSON serializable

ERROR 2025-03-29 20:21:49,764 log 27937 6135328768 Internal Server Error: /api/catalogs
INFO 2025-03-29 20:22:41,243 autoreload 27937 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py changed, reloading.
INFO 2025-03-29 20:22:41,617 autoreload 29095 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:23:23,862 autoreload 29095 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py changed, reloading.
INFO 2025-03-29 20:23:24,180 autoreload 29636 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:23:28,498 autoreload 29636 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:23:28,697 autoreload 29695 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:23:46,329 autoreload 29695 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:23:46,644 autoreload 29903 8545306688 Watching for file changes with StatReloader
ERROR 2025-03-29 20:23:50,912 exception 29903 6190247936 Ocurrió una excepción: Object of type ListSerializer is not JSON serializable
ERROR 2025-03-29 20:23:50,915 exception 29903 6190247936 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py", line 15, in get
    return use_case.get()
           ~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py", line 22, in get
    return ok(CatalogSerializer(catalogs, many=True))
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/helpers/http_responses.py", line 42, in ok
    response = build_response_no_message(data)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/helpers/http_responses.py", line 26, in build_response_no_message
    return JsonResponse(data, safe=False)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/http/response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ListSerializer is not JSON serializable

ERROR 2025-03-29 20:23:50,915 log 29903 6190247936 Internal Server Error: /api/catalogs
INFO 2025-03-29 20:24:13,569 autoreload 29903 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:24:13,858 autoreload 30262 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:26:04,852 autoreload 30262 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:26:05,195 autoreload 31591 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:26:34,136 autoreload 31591 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:26:34,490 autoreload 31972 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:27:39,182 autoreload 31972 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py changed, reloading.
INFO 2025-03-29 20:27:39,629 autoreload 32774 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:27:46,046 autoreload 32774 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-29 20:27:46,333 autoreload 32863 8545306688 Watching for file changes with StatReloader
INFO 2025-03-29 20:28:16,219 autoreload 32863 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-29 20:28:16,533 autoreload 33241 8545306688 Watching for file changes with StatReloader
ERROR 2025-03-29 20:29:02,207 exception 33241 6167113728 Ocurrió una excepción: Got AttributeError when attempting to get a value for field `_id` on serializer `CatalogSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `list` instance.
Original exception text was: 'list' object has no attribute '_id'.
ERROR 2025-03-29 20:29:02,211 exception 33241 6167113728 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'list' object has no attribute '_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/catalog.py", line 23, in get
    return use_case.get_by_id()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py", line 31, in get_by_id
    return ok(CatalogSerializer(catalog).data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `_id` on serializer `CatalogSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `list` instance.
Original exception text was: 'list' object has no attribute '_id'.

ERROR 2025-03-29 20:29:02,212 log 33241 6167113728 Internal Server Error: /api/catalog/67e8534fa303a4cd1b381d22
INFO 2025-03-29 20:32:22,558 autoreload 33241 8545306688 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/catalog_use_case.py changed, reloading.
INFO 2025-03-29 20:32:22,954 autoreload 36209 8545306688 Watching for file changes with StatReloader
