INFO 2025-03-10 01:15:42,004 autoreload 10746 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:15:42,524 autoreload 6460 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:16:53,505 autoreload 6460 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:16:53,810 autoreload 7716 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:16:59,113 autoreload 7716 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:16:59,402 autoreload 7797 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:17:55,855 autoreload 7797 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py changed, reloading.
INFO 2025-03-10 01:17:56,215 autoreload 8797 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:18:09,685 autoreload 8797 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-10 01:18:10,018 autoreload 9069 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:18:18,355 autoreload 9069 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py changed, reloading.
INFO 2025-03-10 01:18:18,774 autoreload 9227 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:18:23,047 autoreload 9227 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/views/__init__.py changed, reloading.
INFO 2025-03-10 01:18:23,242 autoreload 9347 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:19:01,270 autoreload 9347 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-10 01:19:01,578 autoreload 10007 8612886592 Watching for file changes with StatReloader
WARNING 2025-03-10 01:19:32,379 log 10007 6161100800 Forbidden: /api/tree_view_sections
INFO 2025-03-10 01:19:51,093 autoreload 10007 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/urls.py changed, reloading.
INFO 2025-03-10 01:19:51,447 autoreload 10896 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:23:20,043 autoreload 10896 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:23:20,346 autoreload 14539 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:24:56,960 autoreload 14539 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:24:57,303 autoreload 16225 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:25:24,225 autoreload 16225 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:25:24,544 autoreload 16715 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:31:32,118 autoreload 16715 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:31:32,506 autoreload 23114 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:36:26,847 autoreload 23114 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:36:27,244 autoreload 28282 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:36:38,707 autoreload 28282 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:36:39,049 autoreload 28516 8612886592 Watching for file changes with StatReloader
ERROR 2025-03-10 01:36:40,896 exception 28516 6135279616 Ocurri贸 una excepci贸n: list indices must be integers or slices, not str
ERROR 2025-03-10 01:36:40,897 exception 28516 6135279616 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 61, in tree_view
    tree_sections[section['parent']] = []
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

ERROR 2025-03-10 01:36:40,898 log 28516 6135279616 Internal Server Error: /api/tree_view_sections
INFO 2025-03-10 01:37:33,693 autoreload 28516 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:37:34,060 autoreload 29474 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:38:10,088 autoreload 29474 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:38:10,408 autoreload 30161 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:38:51,627 autoreload 30161 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:38:51,935 autoreload 30895 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 01:40:41,911 autoreload 30895 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:40:42,218 autoreload 32824 8612886592 Watching for file changes with StatReloader
ERROR 2025-03-10 01:40:44,254 exception 32824 6199275520 Ocurri贸 una excepci贸n: Object of type ObjectId is not JSON serializable
ERROR 2025-03-10 01:40:44,258 exception 32824 6199275520 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 64, in tree_view
    return ok(tree_sections)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/helpers/http_responses.py", line 42, in ok
    response = build_response_no_message(data)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/helpers/http_responses.py", line 26, in build_response_no_message
    return JsonResponse(data, safe=False)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/http/response.py", line 733, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ObjectId is not JSON serializable

ERROR 2025-03-10 01:40:44,258 log 32824 6199275520 Internal Server Error: /api/tree_view_sections
INFO 2025-03-10 01:42:19,721 autoreload 32824 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 01:42:20,100 autoreload 34531 8612886592 Watching for file changes with StatReloader
ERROR 2025-03-10 01:42:29,030 exception 34531 6204239872 Ocurri贸 una excepci贸n: Object of type ObjectId is not JSON serializable
ERROR 2025-03-10 01:42:29,032 exception 34531 6204239872 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 66, in tree_view
    return HttpResponse(json.dumps(tree_sections), content_type='application/json')
                        ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ObjectId is not JSON serializable

ERROR 2025-03-10 01:42:29,032 log 34531 6204239872 Internal Server Error: /api/tree_view_sections
ERROR 2025-03-10 01:42:30,221 exception 34531 6204239872 Ocurri贸 una excepci贸n: Object of type ObjectId is not JSON serializable
ERROR 2025-03-10 01:42:30,222 exception 34531 6204239872 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 66, in tree_view
    return HttpResponse(json.dumps(tree_sections), content_type='application/json')
                        ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ObjectId is not JSON serializable

ERROR 2025-03-10 01:42:30,222 log 34531 6204239872 Internal Server Error: /api/tree_view_sections
INFO 2025-03-10 02:02:06,301 autoreload 34531 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 02:02:06,666 autoreload 55172 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 02:02:25,136 autoreload 55172 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 02:02:25,535 autoreload 55527 8612886592 Watching for file changes with StatReloader
INFO 2025-03-10 02:03:07,717 autoreload 55527 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 02:03:08,047 autoreload 56271 8612886592 Watching for file changes with StatReloader
ERROR 2025-03-10 02:03:15,441 exception 56271 6128037888 Ocurri贸 una excepci贸n: 'Historial'
ERROR 2025-03-10 02:03:15,442 exception 56271 6128037888 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 64, in tree_view
    tree_sections[section['parent']].append({
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'Historial'

ERROR 2025-03-10 02:03:15,442 log 56271 6128037888 Internal Server Error: /api/tree_view_sections
ERROR 2025-03-10 02:03:16,485 exception 56271 6128037888 Ocurri贸 una excepci贸n: 'Historial'
ERROR 2025-03-10 02:03:16,487 exception 56271 6128037888 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 64, in tree_view
    tree_sections[section['parent']].append({
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'Historial'

ERROR 2025-03-10 02:03:16,487 log 56271 6128037888 Internal Server Error: /api/tree_view_sections
ERROR 2025-03-10 02:04:04,652 exception 56271 6128037888 Ocurri贸 una excepci贸n: 'Historial'
ERROR 2025-03-10 02:04:04,653 exception 56271 6128037888 Detalles del traceback:
Traceback (most recent call last):
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/aemo/Projects/api_sataiga/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/views/section.py", line 31, in get
    return use_case.tree_view()
           ~~~~~~~~~~~~~~~~~~^^
  File "/Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py", line 64, in tree_view
    tree_sections[section['parent']].append({
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'Historial'

ERROR 2025-03-10 02:04:04,654 log 56271 6128037888 Internal Server Error: /api/tree_view_sections
INFO 2025-03-10 02:04:49,864 autoreload 56271 8612886592 /Users/aemo/Projects/api_sataiga/api_sataiga/api/use_cases/section_use_case.py changed, reloading.
INFO 2025-03-10 02:04:50,221 autoreload 58152 8612886592 Watching for file changes with StatReloader
WARNING 2025-03-10 02:06:02,369 log 58152 6175600640 Not Found: /api/stree_view_sections
WARNING 2025-03-10 02:06:19,092 log 58152 6192427008 Not Found: /api/stree_view_sections
WARNING 2025-03-10 13:24:54,125 log 58152 6259732480 Not Found: /apps/logistics/vehicles
WARNING 2025-03-10 13:25:13,645 log 58152 6209253376 Not Found: /apps/logistics/vehicles
WARNING 2025-03-10 13:25:13,750 log 58152 6209253376 Not Found: /favicon.ico
WARNING 2025-03-10 13:29:26,770 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:29:31,306 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:29:39,125 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:52:42,874 log 58152 6209253376 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:52:59,772 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:55:26,726 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:57:54,205 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 13:59:46,799 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 14:04:53,459 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 14:06:38,584 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 14:09:40,802 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 14:09:55,729 log 58152 6377517056 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 14:11:25,807 log 58152 6394343424 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 14:15:25,088 log 58152 6209253376 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:40:32,529 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:40:42,650 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:41:31,267 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:42:44,174 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:44:25,308 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:44:28,561 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:45:42,755 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:58:29,101 log 58152 6377517056 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:59:33,830 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 17:59:55,341 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:00:32,208 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:02:02,764 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:04:10,347 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:11:13,431 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:26:54,477 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:28:31,841 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:29:05,969 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:35:24,155 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:40:25,103 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:50:40,662 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:50:47,358 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:50:52,240 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 18:54:36,404 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 19:18:24,286 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:37:27,416 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:38:20,389 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:39:20,953 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:39:32,384 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:41:28,045 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:42:49,863 log 58152 6377517056 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:43:09,544 log 58152 6394343424 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:43:16,884 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:43:23,636 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:45:03,076 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:45:17,348 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:46:16,459 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:46:53,577 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:47:12,337 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:47:27,372 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:47:55,119 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:48:11,572 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:48:17,922 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:49:05,952 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:49:19,137 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:49:51,402 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:51:04,012 log 58152 6377517056 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:51:09,918 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:51:35,893 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:51:41,362 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:58:12,810 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:58:25,446 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:58:28,613 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:58:34,064 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 20:58:40,971 log 58152 6377517056 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 21:12:51,624 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:52:23,859 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:52:30,592 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:52:40,230 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:53:14,365 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:53:17,334 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:53:19,982 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:53:40,456 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:53:58,765 log 58152 6377517056 Bad Request: /api/login
WARNING 2025-03-10 22:54:01,586 log 58152 6377517056 Bad Request: /api/login
WARNING 2025-03-10 22:54:12,961 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:54:21,964 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:56:27,305 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:58:48,268 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 22:58:56,391 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:01:08,423 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:12:34,169 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:18:51,683 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:18:59,360 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:19:03,759 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:19:44,517 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:19:53,151 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:20:18,718 log 58152 6377517056 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:20:25,426 log 58152 6394343424 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:20:35,908 log 58152 6226079744 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:31:11,337 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:31:58,962 log 58152 6276558848 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:33:36,072 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:34:53,601 log 58152 6310211584 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:35:10,920 log 58152 6327037952 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:35:58,908 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:37:12,135 log 58152 6360690688 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:44:26,186 log 58152 6293385216 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:51:21,092 log 58152 6343864320 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:52:39,509 log 58152 6259732480 Not Found: /dashboard/analytics/projects
WARNING 2025-03-10 23:58:47,143 log 58152 6293385216 Not Found: /dashboard/analytics/projects
